stages:
  - build-fpga

fpga-firmware:
  image:
    name: registry.gitlab.com/chriz2600/quartus-lite:19.1.0
  stage: build-fpga
  script:
    - mkdir -p source/generated
    - if [ ! -f source/generated/slots.v ] ; then echo -e '`define SLOT1 `MODE_1080p60\n`define SLOT2 `MODE_1080i60\n`define SLOT3 `MODE_720p60\n`define SLOT4 `MODE_480p60\n`define SLOT5 `MODE_480i60\n' > source/generated/slots.v ; fi
    - cat source/generated/slots.v | grep '`define SLOT'
    - cat source/generated/slots.v | grep '`define SLOT' | ./prepare-modes.pl > source/generated/video-modes.v
    - cat source/generated/video-modes.v
    - script -qfc "$(printf "%q %q " "/usr/local/bin/quartus_wrapper" "quartus_sh --flow compile lagtester.qpf")" /dev/null
    - md5sum output_files/lagtester.pof
    - ls -alF output_files/lagtester.pof
    - cat output_files/lagtester.fit.rpt | grep '; Total logic elements               ;'
    - cp output_files/lagtester.pof .
  artifacts:
    name: time-sleuth-firmware
    paths:
    - lagtester.pof
  tags:
    - docker
  only:
    - develop
    - master
    - experimental
    - tags
