stages:
  - build-fpga
  #- deploy

fpga-firmware:
  stage: build-fpga
  script:
    - script -qfc "$(printf "%q %q " "/usr/local/bin/quartus_wrapper" "quartus_sh --flow compile lagtester.qpf")" /dev/null
    #- script -qfc "$(printf "%q %q " "/usr/local/bin/quartus_wrapper" "quartus_cpf -c lagtester.cof")" /dev/null
    - cp output_files/lagtester.pof .
  artifacts:
    name: time-sleuth-firmware
    paths:
    - lagtester.pof
    # - output_files/lagtester*.sof
    # - output_files/lagtester*.rpd
    # - output_files/lagtester*.map
  tags:
    - quartus-lite
  only:
    - develop
    - master
    - experimental
    - tags

# firmware-publish:
#   stage: deploy
#   script: create-index-html-ps2
#   artifacts:
#     expire_in: 1 sec
#   dependencies:
#     - esp-firmware
#   tags:
#     - index-gen
#   only:
#     - develop
#     - master
