#!/bin/bash

cd $(dirname $0)

mkdir -p source/generated
if [ ! -f source/generated/slots.v ] ; then echo -e '`define SLOT1 `MODE_1080p60\n`define SLOT2 `MODE_1080i60\n`define SLOT3 `MODE_720p60\n`define SLOT4 `MODE_480p60\n`define SLOT5 `MODE_540p60\n' > source/generated/slots.v ; fi

cat source/generated/slots.v | grep '`define SLOT' | ./prepare-modes.pl > source/generated/video-modes.v

./compile lagtester && \
    md5sum output_files/lagtester.pof && \
    ls -alF output_files/lagtester.pof && \
    cat output_files/lagtester.fit.rpt | grep '; Total logic elements               ;'
