#!/bin/bash

cd $(dirname $0)

./compile lagtester && \
    md5sum output_files/lagtester.pof && \
    ls -alF output_files/lagtester.pof && \
    cat output_files/lagtester.fit.rpt | grep '; Total logic elements               ;'
